[package]
name = "testutils"
version = "0.1.0"
authors = ["zancas <zancas@zingolabs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
